eclair {
  chain = "regtest"

  server {
    port = 9735
  }

  api {
    enabled = true
    binding-ip = "0.0.0.0"
    port = 8080
    password = "eclairpass"
  }

  bitcoind {
    host = "bitcoind"
    rpcport = 18443
    rpcuser = "rpcuser"
    rpcpassword = "rpcpass"
    wallet = "eclair"
    zmqblock = "tcp://bitcoind:28332"
    zmqtx = "tcp://bitcoind:28333"
  }

  on-chain-fees {
    feerate-tolerance {
      ratio-low = 0.00001
      ratio-high = 1000.0
    }
  }

  features {
    option_splice = optional
  }
}
